1. PROCEDURE (Book Appointment)

 CREATE OR REPLACE PROCEDURE BOOK_APPOINTMENT (
  2    P_PATIENT_ID NUMBER,
  3    P_DOCTOR_ID NUMBER,
  4    P_DATE DATE
  5  )
  6  AS
  7  BEGIN
  8    INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, STATUS)
  9    VALUES (
 10      (SELECT NVL(MAX(APPOINTMENT_ID),0)+1 FROM APPOINTMENTS),
 11      P_PATIENT_ID,
 12      P_DOCTOR_ID,
 13      P_DATE,
 14      'BOOKED'
 15    );
 16  END;
 17  /

Procedure created.


# RUN PROCEDURE

 BEGIN
  2    BOOK_APPOINTMENT(1056, 100, DATE '2026-04-15');
  3  END;
  4  /

PL/SQL procedure successfully completed.


2. FUNCTION (Total Billing)

  CREATE OR REPLACE FUNCTION GET_TOTAL_BILL(P_PATIENT_ID NUMBER)
  2  RETURN NUMBER
  3  IS
  4    TOTAL_AMT NUMBER;
  5  BEGIN
  6    SELECT NVL(SUM(AMOUNT),0)
  7    INTO TOTAL_AMT
  8    FROM BILLING
  9    WHERE PATIENT_ID = P_PATIENT_ID;
 10  
 11    RETURN TOTAL_AMT;
 12  END;
 13  /

Function created.


  # RUN FUNCTION

 SELECT GET_TOTAL_BILL(1056) FROM DUAL;

GET_TOTAL_BILL(1056)
--------------------
                9500


# TRIGGER 

Auto-set STATUS = "BOOKED"

 CREATE OR REPLACE TRIGGER TRG_SET_STATUS
  2  BEFORE INSERT ON APPOINTMENTS
  3  FOR EACH ROW
  4  BEGIN
  5    IF :NEW.STATUS IS NULL THEN
  6      :NEW.STATUS := 'BOOKED';
  7    END IF;
  8  END;
  9  /

Trigger created.



# HOW TO TEST
    
INSERT INTO APPOINTMENTS 
VALUES (100, 1056, 100, DATE '2026-04-20', NULL);


CHECK

STATUS=BOOKED







