# PATIENTS TABLE

CREATE TABLE PATIENTS ( PATIENT_ID NUMBER PRIMARY KEY, NAME VARCHAR(50), AGE NUMBER, GENDER VAR
CHAR(10), PHONE VARCHAR(16));

# BILLING TABLE 

CREATE TABLE BILLING (BILL_ID NUMBER PRIMARY KEY, PATIENT_ID NUMBER, AMOUNT NUMBER, BILL_DATE D
ATE, FOREIGN KEY(PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID));

# ROOMS TABLE

CREATE TABLE ROOMS (ROOM_ID NUMBER PRIMARY KEY, ROOM_TYPE VARCHAR(20), AVAILABILITY VARCHAR(10));

# ADMISSIONS TABLE

CREATE TABLE ADMISSSIONS ( ADMISSION_ID NUMBER PRIMARY KEY, PATIENT_ID NUMBER, ROOM_ID NUMBER, 
ADMISSION_DATE DATE, DISCHARGE_DATE DATE, FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (PATIENT_ID),
FOREIGN KEY (ROOM_ID) REFERENCES ROOMS (ROOM_ID));

# MEDICINES TABLE

CREATE TABLE MEDICINES (MEDICINE_ID NUMBER PRIMARY KEY, NAME VARCHAR(50), PRICE NUMBER);


# PRESCRIPTIONS TABLE

CREATE TABLE PRESCRIPTIONS (PRESCRIPTION_ID NUMBER PRIMARY KEY, PATIENT_ID NUMBER, DOCTOR_ID NUMBER
MEDICINE_ID NUMBER, DATE_GIVEN DATE, FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (PATIENT_ID),
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS (DOCTOR_ID), FOREIGN KEY (MEDICINE_ID) REFERENCES MEDIC
INES (MEDICINE_ID));


# DOCTORS TABLE

CREATE TABLE DOCTORS ( DOCTOR_ID NUMBER PRIMARY KEY, NAME VARCHAR(20), SPECIALIZATION VARCHAR(20), PHONE NUMBER);








